// lib/core/services/app_strings.dart
//
// Lightweight app-wide i18n (English / Hindi).
//
// Usage:  Text(tr('Home'))   →   shows "होम" when the user picked Hindi.
//
// Design notes:
//  • Keyed on the ENGLISH source string, so wrapping a literal is a one-liner
//    and there is no separate "key" to keep in sync.
//  • Falls back to the English source whenever language = English OR no Hindi
//    translation exists — it can NEVER throw and never returns an empty string.
//  • Reads the live value from LanguageService, so the same call site renders
//    the right language after the user toggles it (the widget tree rebuilds via
//    the ListenableBuilder wired into main.dart).

import 'language_service.dart';

/// Translate [en] to the active language (English source is the lookup key).
String tr(String en) {
  if (!LanguageService.instance.isHindi) return en;
  final hi = _hi[en];
  return (hi == null || hi.isEmpty) ? en : hi;
}

/// Convenience: pick between an explicit English and Hindi value.
String trPick(String en, String hi) =>
    LanguageService.instance.isHindi && hi.trim().isNotEmpty ? hi : en;

// ─────────────────────────────────────────────────────────────────────────
// English → Hindi dictionary. Add entries here to grow coverage; any string
// not present simply stays in English, so partial coverage is always safe.
// ─────────────────────────────────────────────────────────────────────────
const Map<String, String> _hi = {
  // ── Common / navigation ──
  'Home': 'होम',
  'Profile': 'प्रोफ़ाइल',
  'PROFILE': 'प्रोफ़ाइल',
  'Dashboard': 'डैशबोर्ड',
  'DASHBOARD': 'डैशबोर्ड',
  'Shorts': 'शॉर्ट्स',
  'SHORTS': 'शॉर्ट्स',
  'Leaderboard': 'लीडरबोर्ड',
  'LEADERBOARD': 'लीडरबोर्ड',
  'History': 'इतिहास',
  'HISTORY': 'इतिहास',
  'Login': 'लॉगिन',
  'Logout': 'लॉगआउट',
  'LOGOUT': 'लॉगआउट',
  'Logout?': 'लॉगआउट करें?',
  'Language': 'भाषा',
  'App Language': 'ऐप भाषा',
  'Cancel': 'रद्द करें',
  'Continue': 'जारी रखें',
  'Exit': 'बाहर निकलें',
  'Retry': 'पुनः प्रयास',
  'Go Back': 'वापस जाएँ',
  'OK': 'ठीक है',
  'Submit': 'सबमिट करें',
  'Sending...': 'भेजा जा रहा है...',
  'I Agree': 'मैं सहमत हूँ',
  'Edit': 'संपादित करें',
  'Discard': 'छोड़ें',
  'Keep Editing': 'संपादन जारी रखें',
  'Premium Member': 'प्रीमियम सदस्य',
  'Upgrade to Premium': 'प्रीमियम में अपग्रेड करें',
  'Select Language': 'भाषा चुनें',
  'Choose the language for this test': 'इस टेस्ट की भाषा चुनें',
  'You': 'आप',
  'YOU': 'आप',
  'of': 'में से',
  'No': 'कोई',
  'Loading...': 'लोड हो रहा है...',
  'Latest': 'नवीनतम',

  // ── Errors / network ──
  'Network error. Check your connection.': 'नेटवर्क त्रुटि। अपना कनेक्शन जाँचें।',
  'Network error. Try again.': 'नेटवर्क त्रुटि। फिर से प्रयास करें।',
  'Failed to Load': 'लोड नहीं हो पाया',
  'Could not open link!': 'लिंक नहीं खुल सका!',

  // ── Splash ──
  'New Way to Math': 'गणित का नया तरीका',
  'Update Required': 'अपडेट आवश्यक',
  'A new version of Tunnl is available. Please update to continue.':
      'Tunnl का नया संस्करण उपलब्ध है। जारी रखने के लिए अपडेट करें।',
  'UPDATE NOW': 'अभी अपडेट करें',
  'Under Maintenance': 'रखरखाव जारी है',
  'We are improving Tunnl for you.\nPlease check back shortly.':
      'हम Tunnl को बेहतर बना रहे हैं।\nकृपया थोड़ी देर बाद देखें।',

  // ── Login / OTP / Profile setup ──
  'SPEED MATH CALCULATION': 'स्पीड मैथ कैलकुलेशन',
  'SEND OTP': 'OTP भेजें',
  'What is your number?': 'आपका नंबर क्या है?',
  'New to Tunnl?': 'Tunnl पर नए हैं?',
  'Create Account': 'खाता बनाएँ',
  'Please enter your mobile number': 'कृपया अपना मोबाइल नंबर डालें',
  'Enter valid 10-digit mobile number': 'मान्य 10 अंकों का मोबाइल नंबर डालें',
  'Enter valid Indian mobile number': 'मान्य भारतीय मोबाइल नंबर डालें',
  'Failed to send OTP. Try again.': 'OTP भेजने में विफल। फिर से प्रयास करें।',
  'FAST': 'तेज़',
  'CALCULATION': 'गणना',
  'ACCURATE': 'सटीक',
  'RESULTS': 'परिणाम',
  'IMPROVE': 'सुधारें',
  'TUNNELITY': 'टनलिटी',
  'Please enter complete 6-digit OTP': 'कृपया पूरा 6 अंकों का OTP डालें',
  'Invalid OTP. Please try again.': 'अमान्य OTP। कृपया फिर से प्रयास करें।',
  'OTP resent successfully!': 'OTP फिर से भेज दिया गया!',
  'Failed to resend OTP.': 'OTP फिर से भेजने में विफल।',
  'Verified!': 'सत्यापित!',
  'Verification': 'सत्यापन',
  'Welcome to Tunnl!': 'Tunnl में आपका स्वागत है!',
  'Enter the code sent to your mobile\nnumber':
      'अपने मोबाइल नंबर पर भेजा गया\nकोड डालें',
  "Didn't receive OTP?": 'OTP नहीं मिला?',
  'Resend': 'फिर से भेजें',
  'Resend in': 'फिर से भेजें',
  'VERIFIED': 'सत्यापित',
  'VERIFY OTP': 'OTP सत्यापित करें',
  'Wrong number?': 'गलत नंबर?',
  'Setup Your Profile': 'अपनी प्रोफ़ाइल सेट करें',
  'Help us personalise your Tunnl experience':
      'अपने Tunnl अनुभव को निजी बनाने में हमारी मदद करें',
  'Your Name': 'आपका नाम',
  'YOUR NAME': 'आपका नाम',
  'Enter your full name': 'अपना पूरा नाम डालें',
  'Enter your name': 'अपना नाम डालें',
  'Please enter your name': 'कृपया अपना नाम डालें',
  'Your Class / Exam': 'आपकी कक्षा / परीक्षा',
  'CLASS / EXAM': 'कक्षा / परीक्षा',
  'Please select your class/exam': 'कृपया अपनी कक्षा/परीक्षा चुनें',
  'START MY JOURNEY': 'मेरी यात्रा शुरू करें',
  'Complete your profile to continue': 'जारी रखने के लिए अपनी प्रोफ़ाइल पूरी करें',
  'Failed to save. Try again.': 'सहेजने में विफल। फिर से प्रयास करें।',

  // ── Hub screen ──
  'Test Your Tunnelity': 'अपनी टनलिटी जाँचें',
  'Test Your Tunnlity': 'अपनी टनलिटी जाँचें',
  'TEST YOUR TUNNELITY': 'अपनी टनलिटी जाँचें',
  'Take a quick 10-question speed test': '10 सवालों का तेज़ टेस्ट दें',
  'A quick 10-question speed test': '10 सवालों का तेज़ स्पीड टेस्ट',
  'Your Dashboard': 'आपका डैशबोर्ड',
  'Premium unlocked — explore everything': 'प्रीमियम अनलॉक — सब कुछ देखें',
  'Ticket to Tunnl': 'टनल का टिकट',
  'TICKET TO TUNNL': 'टनल का टिकट',
  'Unlock full access & advanced features': 'पूरी पहुँच और उन्नत सुविधाएँ अनलॉक करें',
  '500 Free Practice MCQs': '500 मुफ़्त अभ्यास MCQ',
  'Practice unlimited questions for free': 'मुफ़्त में असीमित सवाल हल करें',
  'Enter the Tunnel. Master Speed Math.': 'टनल में आएँ। स्पीड मैथ में महारत पाएँ।',

  // ── Quiz / question screen ──
  'Quiz Terms & Conditions': 'क्विज़ नियम और शर्तें',
  'Exit Test?': 'टेस्ट छोड़ें?',
  'Your progress will be lost.\nAre you sure?':
      'आपकी प्रगति खो जाएगी।\nक्या आप निश्चित हैं?',
  'PROGRESS': 'प्रगति',

  // ── Tunnlity ──
  'How fast can you solve?': 'आप कितनी तेज़ी से हल कर सकते हैं?',
  '10 timed questions. Answer quickly and accurately to boost your Tunnelity score. Beat your personal best!':
      '10 समयबद्ध सवाल। अपना टनलिटी स्कोर बढ़ाने के लिए जल्दी और सही जवाब दें। अपना सर्वश्रेष्ठ रिकॉर्ड तोड़ें!',
  'Your Personal Best': 'आपका सर्वश्रेष्ठ',
  'attempt': 'प्रयास',
  'attempts': 'प्रयास',
  'best accuracy': 'सर्वश्रेष्ठ सटीकता',
  'REATTEMPT': 'फिर से प्रयास',
  'START TEST': 'टेस्ट शुरू करें',
  'VIEW SCORE': 'स्कोर देखें',
  'VIEW LEADERBOARD': 'लीडरबोर्ड देखें',
  'Your Tunnelity Score': 'आपका टनलिटी स्कोर',
  'LAST SCORE': 'पिछला स्कोर',
  'PERSONAL BEST': 'सर्वश्रेष्ठ',
  'accuracy': 'सटीकता',
  'Last attempt:': 'पिछला प्रयास:',
  'correct': 'सही',
  'TUNNELITY LEADERBOARD': 'टनलिटी लीडरबोर्ड',
  'Your rank:': 'आपकी रैंक:',
  'Top speed-test scorers': 'शीर्ष स्पीड-टेस्ट स्कोरर',
  'No scores yet': 'अभी कोई स्कोर नहीं',
  'Be the first — take the Tunnelity test!': 'पहले बनें — टनलिटी टेस्ट दें!',
  'pts': 'अंक',

  // ── Solve & Earn / Weekly challenge ──
  'SOLVE & EARN': 'हल करें और जीतें',
  'Solve & Earn': 'हल करें और जीतें',
  'Solve. Compete. Win Rewards!': 'हल करें। मुक़ाबला करें। इनाम जीतें!',
  'No active challenge': 'कोई सक्रिय चैलेंज नहीं',
  'Admin will launch the next weekly challenge soon!':
      'एडमिन जल्द ही अगला साप्ताहिक चैलेंज शुरू करेगा!',
  'Prize Pool': 'इनाम राशि',
  'Prize pool': 'इनाम राशि',
  'RULES': 'नियम',
  'START CHALLENGE': 'चैलेंज शुरू करें',
  'CHALLENGE CLOSED': 'चैलेंज बंद',
  'NO QUESTIONS YET': 'अभी कोई सवाल नहीं',
  'No entries yet': 'अभी कोई प्रविष्टि नहीं',
  'Be the first to attempt this challenge!': 'इस चैलेंज को देने वाले पहले बनें!',
  'WINNER ANNOUNCED': 'विजेता घोषित',
  'Your attempt': 'आपका प्रयास',
  'DAYS\nLEFT': 'दिन\nबाक़ी',
  'top performers win!': 'शीर्ष प्रदर्शक जीतते हैं!',
  'Top performers win rewards!': 'शीर्ष प्रदर्शक इनाम जीतते हैं!',

  // ── Sets / test list ──
  'No sets available yet. Admin will add them soon.':
      'अभी कोई सेट उपलब्ध नहीं। एडमिन जल्द ही जोड़ेगा।',
  'Could not load sets. Please retry.': 'सेट लोड नहीं हो सके। कृपया फिर से प्रयास करें।',
  'Done': 'पूर्ण',
  'Sets': 'सेट',
  'sets': 'सेट',
  'set': 'सेट',
  'Questions each': 'सवाल प्रत्येक',
  'questions each': 'सवाल प्रत्येक',
  'sets completed': 'सेट पूर्ण',
  'Complete previous sets first!': 'पहले पिछले सेट पूरे करें!',
  'Nothing here yet': 'अभी यहाँ कुछ नहीं',
  'SET': 'सेट',
  'PRACTICE TESTS': 'अभ्यास टेस्ट',
  'Practice Tests': 'अभ्यास टेस्ट',
  'Loading sets…': 'सेट लोड हो रहे हैं…',
  'TOTAL SETS': 'कुल सेट',
  'COMPLETED': 'पूर्ण',
  'QUESTIONS': 'सवाल',
  'Questions': 'सवाल',
  'No tests available': 'कोई टेस्ट उपलब्ध नहीं',
  'Admin will publish practice sets soon.': 'एडमिन जल्द ही अभ्यास सेट प्रकाशित करेगा।',
  'Set Locked': 'सेट लॉक है',
  'Complete previous sets to unlock this one.': 'इसे अनलॉक करने के लिए पिछले सेट पूरे करें।',
  'Test': 'टेस्ट',
  'Speed Math': 'स्पीड मैथ',
  'Upgrade to unlock —': 'अनलॉक के लिए अपग्रेड करें —',
  'only': 'मात्र',

  // ── Previous year / MCQ exams ──
  'PREVIOUS YEAR': 'पिछले वर्ष',
  'Select exam to start practising': 'अभ्यास शुरू करने के लिए परीक्षा चुनें',
  'Free exams open. Premium ones need': 'मुफ़्त परीक्षाएँ खुली हैं। प्रीमियम के लिए चाहिए',
  'upgrade.': 'अपग्रेड।',
  'No exams yet': 'अभी कोई परीक्षा नहीं',
  'Admin will publish previous-year papers soon.':
      'एडमिन जल्द ही पिछले वर्ष के पेपर प्रकाशित करेगा।',
  '5000 SPEED MCQS': '5000 स्पीड MCQ',
  'Pick an exam to start practising': 'अभ्यास शुरू करने के लिए परीक्षा चुनें',
  'All Speed MCQs': 'सभी स्पीड MCQ',
  'No exams added yet': 'अभी कोई परीक्षा नहीं जोड़ी गई',
  'Use the "All Speed MCQs" button above for now.':
      'अभी के लिए ऊपर "सभी स्पीड MCQ" बटन का उपयोग करें।',

  // ── Profile ──
  'Notification Settings': 'सूचना सेटिंग्स',
  'Manage your alerts & reminders': 'अपने अलर्ट और रिमाइंडर प्रबंधित करें',
  'Manage alerts & reminders': 'अलर्ट और रिमाइंडर प्रबंधित करें',
  'Daily Practice Reminder': 'दैनिक अभ्यास रिमाइंडर',
  'Remind me to practice every day': 'मुझे हर दिन अभ्यास की याद दिलाएँ',
  'Weekly Challenge Alert': 'साप्ताहिक चैलेंज अलर्ट',
  'Notify when new challenge starts': 'नया चैलेंज शुरू होने पर सूचित करें',
  'Result Announcements': 'परिणाम घोषणाएँ',
  'Solve & Earn winner results': 'हल करें और जीतें विजेता परिणाम',
  'Help & Support': 'सहायता और समर्थन',
  'Email Us': 'हमें ईमेल करें',
  'WhatsApp Support': 'व्हाट्सऐप समर्थन',
  'Chat with us on WhatsApp': 'व्हाट्सऐप पर हमसे चैट करें',
  'Report a Technical Error': 'तकनीकी त्रुटि की रिपोर्ट करें',
  'Tell us about a technical issue': 'किसी तकनीकी समस्या के बारे में बताएँ',
  'Get help from our team': 'हमारी टीम से मदद लें',
  'Switch the whole app. Questions show in this language by default.':
      'पूरा ऐप बदलें। सवाल इसी भाषा में डिफ़ॉल्ट रूप से दिखेंगे।',
  'Describe the problem you faced. Our team will look into it.':
      'आपको आई समस्या बताएँ। हमारी टीम इसे देखेगी।',
  'e.g. App crashes when opening Previous Year...':
      'जैसे, पिछला वर्ष खोलने पर ऐप क्रैश होता है...',
  'Please describe the issue.': 'कृपया समस्या बताएँ।',
  'Thank you! Your report was submitted.': 'धन्यवाद! आपकी रिपोर्ट सबमिट हो गई।',
  'Could not submit. Please try again.': 'सबमिट नहीं हो सका। कृपया फिर से प्रयास करें।',
  'Are you sure you want to logout?': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
  'Member since': 'सदस्य',
  'RANK': 'रैंक',
  'XP': 'XP',
  'STREAK': 'स्ट्रीक',
  'ACCURACY': 'सटीकता',
  'Accuracy': 'सटीकता',
  'PERFORMANCE': 'प्रदर्शन',
  'Attempted': 'प्रयास किए',
  'Correct': 'सही',
  'Wrong': 'गलत',
  'TUNNL PREMIUM': 'Tunnl प्रीमियम',
  'Unlock Premium': 'प्रीमियम अनलॉक करें',
  'Full access — Lifetime': 'पूरी पहुँच — आजीवन',
  'Get complete access @': 'पूरी पहुँच पाएँ @',
  'ACTIVE': 'सक्रिय',
  'Test History': 'टेस्ट इतिहास',
  'View all past tests': 'सभी पिछले टेस्ट देखें',
  'Notifications': 'सूचनाएँ',
  'App Version': 'ऐप संस्करण',

  // ── History ──
  'Search exam, category...': 'परीक्षा, श्रेणी खोजें...',
  'Latest First': 'नवीनतम पहले',
  'Highest Score': 'उच्चतम स्कोर',
  'Lowest Score': 'न्यूनतम स्कोर',
  'Failed to load history': 'इतिहास लोड करने में विफल',
  'All caught up!': 'सब देख लिया!',
  'Track your performance over time': 'समय के साथ अपना प्रदर्शन देखें',
  'TOTAL TESTS': 'कुल टेस्ट',
  'AVERAGE SCORE': 'औसत स्कोर',
  'BEST SCORE': 'सर्वश्रेष्ठ स्कोर',
  'Perfect!': 'बढ़िया!',
  'AVG SPEED': 'औसत गति',
  'AVG TIME': 'औसत समय',
  'SCORE': 'स्कोर',
  'No results for': 'इसके लिए कोई परिणाम नहीं',
  'No history yet!\nStart solving to see results here.':
      'अभी कोई इतिहास नहीं!\nपरिणाम देखने के लिए हल करना शुरू करें।',

  // ── Leaderboard ──
  'No rankings yet': 'अभी कोई रैंकिंग नहीं',
  'Solve some quizzes to climb the board!': 'बोर्ड पर चढ़ने के लिए कुछ क्विज़ हल करें!',
  'Total XP earned': 'कुल अर्जित XP',
  'WEEKLY': 'साप्ताहिक',
  'MONTHLY': 'मासिक',
  'ALL TIME': 'सर्वकालिक',

  // ── Result ──
  'Excellent! You are in the top tier 🔥': 'शानदार! आप शीर्ष श्रेणी में हैं 🔥',
  'Good effort! Keep pushing!': 'अच्छा प्रयास! ऐसे ही लगे रहें!',
  'Keep practicing to improve!': 'सुधार के लिए अभ्यास जारी रखें!',
  'more correct → reach Top 20!': 'और सही → टॉप 20 में पहुँचें!',
  'Skipped': 'छोड़ा',
  'RESULT': 'परिणाम',
  'REVIEW': 'समीक्षा',
  'Your Ranking': 'आपकी रैंकिंग',
  'student': 'छात्र',
  'students': 'छात्र',
  'attempted this set': 'ने यह सेट दिया',
  'RETRY TEST': 'टेस्ट फिर से दें',
  'No review data available.': 'कोई समीक्षा डेटा उपलब्ध नहीं।',
  'Solution': 'हल',
  'Timed out': 'समय समाप्त',
  'Answered in': 'जवाब दिया',
  'Unlock Premium\nContent': 'प्रीमियम सामग्री\nअनलॉक करें',
  'ELITE\nACCESS': 'एलीट\nएक्सेस',
  'UNLOCK NOW': 'अभी अनलॉक करें',
  'Tunnl Tricks — strategies & shortcuts': 'Tunnl ट्रिक्स — रणनीतियाँ और शॉर्टकट',
  '5000 Speed Math MCQs': '5000 स्पीड मैथ MCQ',
  '500 Simplification Questions': '500 सरलीकरण सवाल',
  'Shorts — quick math tip videos': 'शॉर्ट्स — तेज़ गणित टिप वीडियो',
  'Daily Practice Sets': 'दैनिक अभ्यास सेट',
  'Previous Year Questions': 'पिछले वर्ष के सवाल',
  'Solve & Earn rewards': 'हल करें और इनाम जीतें',
  'Leaderboard Access': 'लीडरबोर्ड एक्सेस',

  // ── Premium ──
  '500 Free MCQs': '500 मुफ़्त MCQ',
  '10 sets × 50 questions': '10 सेट × 50 सवाल',
  '10 question speed test': '10 सवालों का स्पीड टेस्ट',
  'Daily Dose': 'डेली डोज़',
  '1 question daily pop-up': 'रोज़ 1 सवाल पॉप-अप',
  'Tunnl Tricks': 'Tunnl ट्रिक्स',
  'Powerful strategies & shortcuts': 'शक्तिशाली रणनीतियाँ और शॉर्टकट',
  'Unlimited practice questions': 'असीमित अभ्यास सवाल',
  'Master simplification tricks': 'सरलीकरण ट्रिक्स में महारत',
  'Quick math tip videos': 'तेज़ गणित टिप वीडियो',
  "Today's set in dashboard": 'डैशबोर्ड में आज का सेट',
  'Complete PYQ access': 'पूरी PYQ पहुँच',
  'Earn rewards by solving': 'हल करके इनाम कमाएँ',
  'Compete with 12,000+ students': '12,000+ छात्रों से मुक़ाबला करें',
  'AS A GUEST': 'अतिथि के रूप में',
  'Free forever': 'हमेशा मुफ़्त',
  'Premium —': 'प्रीमियम —',
  'one time': 'एक बार',
  'UNLOCK FULL ACCESS': 'पूरी पहुँच अनलॉक करें',
  'One-time payment — Lifetime access': 'एक बार भुगतान — आजीवन पहुँच',
  'ONE TIME': 'एक बार',
  'LIFETIME': 'आजीवन',
  'FEATURES': 'सुविधाएँ',
  'UPGRADE': 'अपग्रेड',
  'Tunnel Premium': 'Tunnel प्रीमियम',
  'One-time • Lifetime access': 'एक बार • आजीवन पहुँच',
  'after discount': 'छूट के बाद',
  'Have a coupon?': 'कूपन है?',
  'ENTER CODE': 'कोड डालें',
  'Enter a coupon code first.': 'पहले एक कूपन कोड डालें।',
  'REMOVE': 'हटाएँ',
  'APPLY': 'लागू करें',
  'PAY': 'भुगतान करें',
  '& UNLOCK NOW': 'और अभी अनलॉक करें',
  'Secured by Razorpay  •  One-time payment': 'Razorpay द्वारा सुरक्षित  •  एक बार भुगतान',
  'Payment Successful!': 'भुगतान सफल!',
  'Welcome to Tunnl Premium!\nAll features unlocked 🎉':
      'Tunnl प्रीमियम में आपका स्वागत है!\nसभी सुविधाएँ अनलॉक 🎉',
  'Valid:': 'मान्य:',
  'EXPLORE DASHBOARD': 'डैशबोर्ड देखें',

  // ── Tricks ──
  'TUNNL TRICKS': 'Tunnl ट्रिक्स',
  'Tips & Tricks to master Math': 'गणित में महारत के टिप्स और ट्रिक्स',
  'Tricks': 'ट्रिक्स',
  'Free': 'मुफ़्त',
  'tricks free': 'ट्रिक्स मुफ़्त',
  'Upgrade for': 'इसके लिए अपग्रेड करें',
  'premium tricks': 'प्रीमियम ट्रिक्स',
  'Upgrade to Premium —': 'प्रीमियम में अपग्रेड करें —',
  'No tricks yet': 'अभी कोई ट्रिक नहीं',
  'Admin will publish them soon.': 'एडमिन जल्द ही प्रकाशित करेगा।',
  'CHAPTER': 'अध्याय',
  'ARTICLE': 'लेख',
  'VIDEO': 'वीडियो',
  'No content yet': 'अभी कोई सामग्री नहीं',
  'Admin will publish this trick soon.': 'एडमिन जल्द ही यह ट्रिक प्रकाशित करेगा।',
  'No playable video set': 'कोई चलने योग्य वीडियो नहीं',
  'Admin can add a YouTube link or upload a video.':
      'एडमिन यूट्यूब लिंक जोड़ सकता है या वीडियो अपलोड कर सकता है।',
  'Duration:': 'अवधि:',

  // ── Daily dose ──
  'DAILY DOSE': 'डेली डोज़',
  'Example': 'उदाहरण',
  'Pro Tip': 'प्रो टिप',
  'WATCH VIDEO': 'वीडियो देखें',
  'GOT IT ✓': 'समझ गया ✓',

  // ── Shorts ──
  'Quick Math Tips & Tricks': 'तेज़ गणित टिप्स और ट्रिक्स',
  'Videos': 'वीडियो',
  'No shorts available yet!': 'अभी कोई शॉर्ट्स उपलब्ध नहीं!',
  'shorts.': 'शॉर्ट्स।',
  'Admin will add videos soon.': 'एडमिन जल्द ही वीडियो जोड़ेगा।',

  // ── Edit profile ──
  'EDIT PROFILE': 'प्रोफ़ाइल संपादित करें',
  'Discard changes?': 'बदलाव छोड़ें?',
  'Your edits will be lost. Are you sure?': 'आपके बदलाव खो जाएँगे। क्या आप निश्चित हैं?',
  'Profile updated!': 'प्रोफ़ाइल अपडेट हुई!',
  'Failed to update. Try again.': 'अपडेट विफल। फिर से प्रयास करें।',
  'PHONE': 'फ़ोन',
  '— not set —': '— सेट नहीं —',
  'Phone copied': 'फ़ोन कॉपी हुआ',
  'SAVE CHANGES': 'बदलाव सहेजें',
  'NO CHANGES TO SAVE': 'सहेजने के लिए कोई बदलाव नहीं',
  'Name cannot be empty': 'नाम खाली नहीं हो सकता',

  // ── Dashboard ──
  'Practice unlimited MCQs': 'असीमित MCQ अभ्यास करें',
  'Learn powerful strategies & tricks': 'शक्तिशाली रणनीतियाँ और ट्रिक्स सीखें',
  'Watch quick math tips': 'तेज़ गणित टिप्स देखें',
  'Daily challenge sets': 'दैनिक चैलेंज सेट',
  'Earn rewards by solving quizzes': 'क्विज़ हल करके इनाम कमाएँ',
  'Good Morning': 'सुप्रभात',
  'Good Afternoon': 'नमस्कार',
  'Good Evening': 'शुभ संध्या',
  'Mathletes': 'मैथलीट्स',
  'Daily Practice MCQs': 'दैनिक अभ्यास MCQ',
  'All daily sets': 'सभी दैनिक सेट',
  "Today's set — Free": 'आज का सेट — मुफ़्त',
  'What to ': 'क्या ',
  'Explore?': 'देखें?',
  'Dive into the high-dimensional logic of the\nmathematical void. Select a node to begin.':
      'गणित की दुनिया के गहरे तर्क में उतरें।\nशुरू करने के लिए एक विकल्प चुनें।',
  'LEARN': 'सीखें',
  'PRACTICE': 'अभ्यास',
};
